import { User, ChatRoom, ChatMessage, Notice, Complaint, Vote, MarketItem } from '@/types';

export const APARTMENT_NAME = "설악디엘본아파트";
export const TOTAL_HOUSEHOLDS = 420;

export const BUILDINGS = [
  "101동", "102동", "103동", "104동", "105동", "106동"
];

export const DEMO_USERS: User[] = [
  {
    id: "user-resident-1",
    name: "김주민",
    role: "resident",
    apartmentName: APARTMENT_NAME,
    building: "101동",
    unit: "1203호",
    phone: "010-1234-5678",
    avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=JuminKim",
    isVerified: true,
    joinedAt: "2025.03.12",
  },
  {
    id: "user-rep-101",
    name: "이대표",
    role: "representative",
    apartmentName: APARTMENT_NAME,
    building: "101동",
    unit: "502호",
    roleTitle: "101동 동대표 👑",
    phone: "010-2345-6789",
    avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=LeeRep",
    isVerified: true,
    joinedAt: "2024.11.01",
  },
  {
    id: "user-resident-2",
    name: "박이웃",
    role: "resident",
    apartmentName: APARTMENT_NAME,
    building: "102동",
    unit: "801호",
    phone: "010-3456-7890",
    avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=ParkNeighbor",
    isVerified: true,
    joinedAt: "2025.01.20",
  },
  {
    id: "user-manager-1",
    name: "정소장",
    role: "manager",
    apartmentName: APARTMENT_NAME,
    building: "관리동",
    unit: "관리사무소",
    roleTitle: "관리사무소장 🏢",
    phone: "033-631-4567",
    avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=ManagerJeong",
    isVerified: true,
    joinedAt: "2023.06.01",
  },
  {
    id: "user-facility-1",
    name: "최과장",
    role: "manager",
    apartmentName: APARTMENT_NAME,
    building: "관리동",
    unit: "시설관리팀",
    roleTitle: "시설관리팀장 🛠️",
    phone: "033-631-4568",
    avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=ChoiFacility",
    isVerified: true,
    joinedAt: "2023.08.15",
  }
];

export const INITIAL_CHAT_ROOMS: ChatRoom[] = [
  {
    id: "room-complex",
    name: "📢 단지 전체 광장 톡방",
    type: "complex",
    description: "설악디엘본아파트 420세대 전체 입주민이 자유롭게 소통하는 열린 광장입니다.",
    memberCount: 392,
    unreadCount: 2,
    lastMessage: "내일 단지 내 알뜰장터 오전 10시부터 중앙광장에서 진행됩니다!",
    lastMessageTime: "오후 5:45",
    pinnedNotice: "📌 [필독] 이번 주 토요일 지하주차장 소방시설 종합점검 안내",
  },
  {
    id: "room-101",
    name: "🏢 101동 이웃 소통방",
    type: "building",
    targetBuilding: "101동",
    description: "설악디엘본 101동 입주민들만의 프라이빗 소통 공간입니다.",
    memberCount: 68,
    unreadCount: 0,
    lastMessage: "101동 1~2호 라인 승강기 점검 완료되어 정상 운행 중입니다.",
    lastMessageTime: "오후 4:20",
    pinnedNotice: "📌 101동 재활용 분리수거 요일: 매주 화/금요일 저녁",
  },
  {
    id: "room-102",
    name: "🏢 102동 이웃 소통방",
    type: "building",
    targetBuilding: "102동",
    description: "설악디엘본 102동 입주민들만의 프라이빗 소통 공간입니다.",
    memberCount: 71,
    unreadCount: 1,
    lastMessage: "혹시 102동 1층 로비에 우산 두고 가신 분 계신가요?",
    lastMessageTime: "오후 3:10",
  },
  {
    id: "room-103",
    name: "🏢 103동 이웃 소통방",
    type: "building",
    targetBuilding: "103동",
    description: "설악디엘본 103동 입주민들만의 프라이빗 소통 공간입니다.",
    memberCount: 65,
    unreadCount: 0,
    lastMessage: "모두 편안한 저녁시간 보내세요~",
    lastMessageTime: "어제",
  },
  {
    id: "room-104",
    name: "🏢 104동 이웃 소통방",
    type: "building",
    targetBuilding: "104동",
    description: "설악디엘본 104동 입주민들만의 프라이빗 소통 공간입니다.",
    memberCount: 69,
    unreadCount: 0,
    lastMessage: "104동 앞 산책로 꽃길 너무 예쁘네요 🌸",
    lastMessageTime: "어제",
  },
  {
    id: "room-105",
    name: "🏢 105동 이웃 소통방",
    type: "building",
    targetBuilding: "105동",
    description: "설악디엘본 105동 입주민들만의 프라이빗 소통 공간입니다.",
    memberCount: 63,
    unreadCount: 0,
    lastMessage: "지하 1층 주차 구역 청소 완료되었습니다.",
    lastMessageTime: "2일 전",
  },
  {
    id: "room-106",
    name: "🏢 106동 이웃 소통방",
    type: "building",
    targetBuilding: "106동",
    description: "설악디엘본 106동 입주민들만의 프라이빗 소통 공간입니다.",
    memberCount: 67,
    unreadCount: 0,
    lastMessage: "106동 라인 택배함 정상 작동 중입니다.",
    lastMessageTime: "3일 전",
  },
  {
    id: "room-rep",
    name: "⚖️ [입대위] 설악디엘본 입주자대표회의",
    type: "rep_council",
    description: "101동~106동 동대표 및 관리사무소 임원 전용 비공개 안건 회의 채널입니다.",
    memberCount: 8,
    unreadCount: 3,
    lastMessage: "지하주차장 차단기 스마트 번호인식 시스템 입찰 안건 상정했습니다.",
    lastMessageTime: "오후 2:15",
    pinnedNotice: "📌 제12차 정기 입대위 회의: 8월 28일(목) 19:30 관리동 2층 회의실",
  },
  {
    id: "room-manager-1on1",
    name: "💬 [관리사무소] 1:1 민원 및 행정상담실",
    type: "manager_1on1",
    description: "관리사무소와 1:1로 실시간 민원, 시설 고장, 주차 등록 등을 상담하세요.",
    memberCount: 2,
    unreadCount: 0,
    lastMessage: "접수해주신 세대 누수 점검 건 내일 오전 10시 기사님 방문 예정입니다.",
    lastMessageTime: "오전 11:30",
  }
];

export const INITIAL_MESSAGES: Record<string, ChatMessage[]> = {
  "room-complex": [
    {
      id: "msg-c-1",
      roomId: "room-complex",
      senderId: "user-manager-1",
      senderName: "정소장",
      senderRole: "manager",
      senderBuilding: "관리동",
      senderUnit: "관리사무소",
      senderRoleTitle: "관리사무소장 🏢",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=ManagerJeong",
      content: "설악디엘본아파트 420세대 입주민 여러분 안녕하십니까! 이번 주 금요일(28일) 단지 내 소독 및 방역 작업이 예정되어 있으니 베란다 창문을 닫아주시기 바랍니다.",
      timestamp: "오후 2:30",
      unreadMembersCount: 0,
      isNotice: true,
    },
    {
      id: "msg-c-2",
      roomId: "room-complex",
      senderId: "user-resident-1",
      senderName: "김주민",
      senderRole: "resident",
      senderBuilding: "101동",
      senderUnit: "1203호",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=JuminKim",
      content: "소독 일정 공유 감사합니다! 혹시 저녁 시간대 지하주차장 2층 전기차 충전 구역 불법주차 단속도 계속 진행되나요?",
      timestamp: "오후 3:15",
      unreadMembersCount: 0,
    },
    {
      id: "msg-c-3",
      roomId: "room-complex",
      senderId: "user-rep-101",
      senderName: "이대표",
      senderRole: "representative",
      senderBuilding: "101동",
      senderUnit: "502호",
      senderRoleTitle: "101동 동대표 👑",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=LeeRep",
      content: "네, 김주민님! 이번 입대위 회의에서 전기차 충전구역 주차위반 계도 스티커 부착을 강화하기로 의결했습니다. 모두 쾌적한 주차환경을 위해 협조 부탁드립니다.",
      timestamp: "오후 3:40",
      unreadMembersCount: 0,
    },
    {
      id: "msg-c-4",
      roomId: "room-complex",
      senderId: "user-resident-2",
      senderName: "박이웃",
      senderRole: "resident",
      senderBuilding: "102동",
      senderUnit: "801호",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=ParkNeighbor",
      content: "내일 단지 내 알뜰장터 오전 10시부터 중앙광장에서 진행됩니다! 아이들 장난감이랑 동화책 많이 나눔하러 나갈게요~",
      timestamp: "오후 5:45",
      unreadMembersCount: 0,
    }
  ],
  "room-101": [
    {
      id: "msg-101-1",
      roomId: "room-101",
      senderId: "user-rep-101",
      senderName: "이대표",
      senderRole: "representative",
      senderBuilding: "101동",
      senderUnit: "502호",
      senderRoleTitle: "101동 동대표 👑",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=LeeRep",
      content: "설악디엘본 101동 이웃 여러분 안녕하세요! 이번 주말 101동 출입구 화단 봄꽃 식재 작업이 있습니다. 자원봉사 환영합니다.",
      timestamp: "오전 10:00",
      unreadMembersCount: 0,
    },
    {
      id: "msg-101-2",
      roomId: "room-101",
      senderId: "user-resident-1",
      senderName: "김주민",
      senderRole: "resident",
      senderBuilding: "101동",
      senderUnit: "1203호",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=JuminKim",
      content: "저희 가족도 토요일 오전에 아이와 함께 화단 꾸미기 참여하겠습니다!",
      timestamp: "오전 11:20",
      unreadMembersCount: 0,
    },
    {
      id: "msg-101-3",
      roomId: "room-101",
      senderId: "user-facility-1",
      senderName: "최과장",
      senderRole: "manager",
      senderBuilding: "관리동",
      senderUnit: "시설관리팀",
      senderRoleTitle: "시설관리팀장 🛠️",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=ChoiFacility",
      content: "101동 1~2호 라인 승강기 점검 완료되어 정상 운행 중입니다. 불편을 드려 죄송했습니다.",
      timestamp: "오후 4:20",
      unreadMembersCount: 0,
    }
  ],
  "room-102": [
    {
      id: "msg-102-1",
      roomId: "room-102",
      senderId: "user-resident-2",
      senderName: "박이웃",
      senderRole: "resident",
      senderBuilding: "102동",
      senderUnit: "801호",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=ParkNeighbor",
      content: "혹시 102동 1층 로비에 우산 두고 가신 분 계신가요? 경비실에 맡겨두었습니다.",
      timestamp: "오후 3:10",
      unreadMembersCount: 0,
    }
  ],
  "room-103": [
    {
      id: "msg-103-1",
      roomId: "room-103",
      senderId: "user-resident-1",
      senderName: "이웃103",
      senderRole: "resident",
      senderBuilding: "103동",
      senderUnit: "602호",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=Resident103",
      content: "103동 이웃 여러분 모두 편안한 저녁시간 보내세요~",
      timestamp: "어제",
      unreadMembersCount: 0,
    }
  ],
  "room-104": [
    {
      id: "msg-104-1",
      roomId: "room-104",
      senderId: "user-resident-1",
      senderName: "행복104",
      senderRole: "resident",
      senderBuilding: "104동",
      senderUnit: "704호",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=Resident104",
      content: "104동 앞 산책로 꽃길 너무 예쁘네요 🌸",
      timestamp: "어제",
      unreadMembersCount: 0,
    }
  ],
  "room-105": [
    {
      id: "msg-105-1",
      roomId: "room-105",
      senderId: "user-facility-1",
      senderName: "최과장",
      senderRole: "manager",
      senderBuilding: "관리동",
      senderUnit: "시설관리팀",
      senderRoleTitle: "시설관리팀장 🛠️",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=ChoiFacility",
      content: "105동 지하 1층 주차 구역 청소 완료되었습니다.",
      timestamp: "2일 전",
      unreadMembersCount: 0,
    }
  ],
  "room-106": [
    {
      id: "msg-106-1",
      roomId: "room-106",
      senderId: "user-resident-1",
      senderName: "설악106",
      senderRole: "resident",
      senderBuilding: "106동",
      senderUnit: "1102호",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=Resident106",
      content: "106동 라인 택배함 정상 작동 중입니다.",
      timestamp: "3일 전",
      unreadMembersCount: 0,
    }
  ],
  "room-rep": [
    {
      id: "msg-rep-1",
      roomId: "room-rep",
      senderId: "user-manager-1",
      senderName: "정소장",
      senderRole: "manager",
      senderBuilding: "관리동",
      senderUnit: "관리사무소",
      senderRoleTitle: "관리사무소장 🏢",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=ManagerJeong",
      content: "101동~106동 동대표님들, 설악디엘본 8월 결산 보고서 및 장기수선충당금 사용 계획안을 공유합니다. 사전 검토 부탁드립니다.",
      timestamp: "오후 1:30",
      unreadMembersCount: 0,
    },
    {
      id: "msg-rep-2",
      roomId: "room-rep",
      senderId: "user-rep-101",
      senderName: "이대표",
      senderRole: "representative",
      senderBuilding: "101동",
      senderUnit: "502호",
      senderRoleTitle: "101동 동대표 👑",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=LeeRep",
      content: "지하주차장 차단기 스마트 번호인식 시스템 입찰 안건 상정했습니다. 420세대 주민투표 안건으로 부의할지 논의 필요합니다.",
      timestamp: "오후 2:15",
      unreadMembersCount: 0,
    }
  ],
  "room-manager-1on1": [
    {
      id: "msg-m-1",
      roomId: "room-manager-1on1",
      senderId: "user-resident-1",
      senderName: "김주민",
      senderRole: "resident",
      senderBuilding: "101동",
      senderUnit: "1203호",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=JuminKim",
      content: "관리사무소님 안녕하세요, 주방 싱크대 배관 쪽에서 미세하게 누수가 있어 점검 요청드립니다.",
      timestamp: "오전 10:45",
      unreadMembersCount: 0,
    },
    {
      id: "msg-m-2",
      roomId: "room-manager-1on1",
      senderId: "user-manager-1",
      senderName: "정소장",
      senderRole: "manager",
      senderBuilding: "관리동",
      senderUnit: "관리사무소",
      senderRoleTitle: "관리사무소 🏢",
      avatarUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=ManagerJeong",
      content: "안녕하세요 김주민님(101동 1203호). 접수해주신 세대 누수 점검 건 내일 오전 10시 기사님 방문 예정입니다.",
      timestamp: "오전 11:30",
      unreadMembersCount: 0,
    }
  ]
};

export const INITIAL_NOTICES: Notice[] = [
  {
    id: "notice-1",
    title: "🚨 [긴급] 단지 내 급수 가압펌프 정기교체에 따른 단수 안내",
    content: "안정적인 급수 공급을 위해 8월 29일(금) 13:00 ~ 16:00 (3시간) 동안 설악디엘본 420세대 전 세대 단수가 실시됩니다. 세대에서는 미리 사용할 식수와 생활용수를 확보해주시기 바랍니다.",
    category: "urgent",
    author: "관리사무소",
    authorRole: "관리사무소장",
    createdAt: "2026.08.25",
    views: 489,
    isPinned: true,
  },
  {
    id: "notice-2",
    title: "📋 2026년 하반기 차량 등록 및 주차 스티커 일제 갱신 안내",
    content: "외부 불법 주차 차량을 근절하고 설악디엘본 입주민 주차 편의를 도모하고자 주차 스티커를 전면 갱신합니다. 관리사무소 방문 또는 모바일 앱을 통해 차량등록증을 첨부하여 신청해주시기 바랍니다.",
    category: "general",
    author: "관리사무소",
    authorRole: "관리사무소장",
    createdAt: "2026.08.24",
    views: 312,
    isPinned: true,
  },
  {
    id: "notice-3",
    title: "🌿 단지 내 가을맞이 어린이 벼룩시장 & 나눔 축제 개최",
    content: "설악디엘본 입주민 여러분의 화합을 위해 9월 6일(토) 단지 중앙 분수광장에서 나눔 장터가 열립니다. 참가 신청은 본 앱 '장터/나눔' 코너를 통해 자유롭게 등록해주세요.",
    category: "event",
    author: "입주자대표회의",
    authorRole: "입대위 회장단",
    createdAt: "2026.08.22",
    views: 205,
    isPinned: false,
  }
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: "comp-1",
    title: "101동 지하 2층 주차장 기둥 부근 가로등 점등 불량",
    content: "101동 지하 2층 E구역 주차 기둥 쪽 LED 조명이 깜빡거리다가 꺼져서 야간 주차 시 매우 어둡습니다. 점검 및 교체 부탁드립니다.",
    category: "facility",
    authorId: "user-resident-1",
    authorName: "김주민",
    authorBuilding: "101동",
    authorUnit: "1203호",
    isPrivate: false,
    status: "in_progress",
    createdAt: "2026.08.25 14:20",
    updatedAt: "2026.08.25 16:00",
    managerReply: {
      repliedBy: "최과장",
      roleTitle: "시설관리팀장",
      content: "금일 오후 현장 확인 완료하였으며, 신규 LED 등기구 자재 입고 후 내일 오전 11시 교체 작업 예정입니다.",
      repliedAt: "2026.08.25 16:00",
    }
  },
  {
    id: "comp-2",
    title: "늦은 밤 배달 오토바이 단지 내 과속 및 경적 소음 민원",
    content: "야간 11시 이후 배달 오토바이들이 보행자 도로로 진입하거나 과속하는 경우가 많아 아이들 안전과 소음 피해가 우려됩니다. 정문 차단기 안내 조치 부탁드립니다.",
    category: "noise",
    authorId: "user-resident-2",
    authorName: "박이웃",
    authorBuilding: "102동",
    authorUnit: "801호",
    isPrivate: false,
    status: "resolved",
    createdAt: "2026.08.23 23:10",
    updatedAt: "2026.08.24 10:30",
    managerReply: {
      repliedBy: "정소장",
      roleTitle: "관리사무소장",
      content: "보안경비 초소에 지시하여 야간 배달 기사님 진입 시 서행 및 지상 보행로 진입 금지 계도를 의무화하도록 조치 완료했습니다.",
      repliedAt: "2026.08.24 10:30",
    }
  }
];

export const INITIAL_VOTES: Vote[] = [
  {
    id: "vote-1",
    title: "⚡ 지하주차장 급속 전기차 충전기 4기 추가 설치 찬반 투표",
    description: "설악디엘본 420세대 주차 환경 개선을 위해 정부 지원 사업과 연계하여 입주민 자부담 없이 지하 2층 유휴 공간에 급속 충전기 4기를 확충하고자 합니다.",
    author: "입주자대표회의",
    authorRole: "입대위 회장",
    deadline: "2026.08.31",
    totalVotes: 318,
    votedUserIds: ["user-resident-1", "user-rep-101"],
    status: "ongoing",
    createdAt: "2026.08.20",
    options: [
      { id: "opt-1", text: "찬성 (전기차 인프라 확대 및 충전난 해소)", votesCount: 275 },
      { id: "opt-2", text: "반대 (일반 주차 구역 축소 우려)", votesCount: 35 },
      { id: "opt-3", text: "기권 / 기타 의견", votesCount: 8 }
    ]
  },
  {
    id: "vote-2",
    title: "🏋️ 단지 내 주민 커뮤니티 헬스장 야간 24시간 무인 운영 도입의 건",
    description: "직장인 입주민들의 편의를 위해 지문/앱 인증 출입 시스템을 설치하여 헬스장을 24시간 개방하는 안건입니다.",
    author: "입주자대표회의",
    authorRole: "101동 동대표",
    deadline: "2026.09.05",
    totalVotes: 210,
    votedUserIds: [],
    status: "ongoing",
    createdAt: "2026.08.23",
    options: [
      { id: "opt-2-1", text: "찬성 (야간 운동 편의 증대)", votesCount: 175 },
      { id: "opt-2-2", text: "반대 (안전 및 관리 비용 증가 우려)", votesCount: 28 },
      { id: "opt-2-3", text: "보류 (현행 23시 마감 유지)", votesCount: 7 }
    ]
  }
];

export const INITIAL_MARKET_ITEMS: MarketItem[] = [
  {
    id: "market-1",
    title: "👶 스토케 유모차 & 신생아 시트 무료 나눔합니다",
    description: "아이가 부쩍 커서 이제 사용하지 않아 깨끗이 세탁 후 나눔합니다. 101동 1층 필로티에서 직거래 원해요!",
    price: 0,
    isFree: true,
    status: "selling",
    authorId: "user-resident-1",
    authorName: "김주민",
    authorBuilding: "101동",
    authorUnit: "1203호",
    locationTip: "101동 로비 앞 직거래",
    createdAt: "방금 전",
    imageUrl: "https://images.unsplash.com/photo-1591088398332-8a7791972843?w=500&auto=format&fit=crop&q=60",
    likesCount: 14,
    chatsCount: 3,
  },
  {
    id: "market-2",
    title: "⛺ 코베아 4인용 패밀리 텐트 (실사용 2회 S급)",
    description: "작년에 구매하고 2번 피칭한 거의 새 제품입니다. 이사 정리로 저렴하게 내놓습니다.",
    price: 120000,
    isFree: false,
    status: "selling",
    authorId: "user-resident-2",
    authorName: "박이웃",
    authorBuilding: "102동",
    authorUnit: "801호",
    locationTip: "102동 지하 1층 주차장 앞",
    createdAt: "2시간 전",
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=500&auto=format&fit=crop&q=60",
    likesCount: 8,
    chatsCount: 2,
  }
];
